on:
  push:
    branches-ignore:
      - master

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: yarn - setup & compile
        run: |
          yarn
          yarn run compile
      - name: Run headless tests
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: yarn run test
